[0m17:20:39.088994 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f16beefac10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f16be07c880>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f16be07c970>]}


============================== 17:20:39.140711 | 718f2703-5c86-4bea-bae2-df4fd7ee1c3e ==============================
[0m17:20:39.140711 [info ] [MainThread]: Running with dbt=1.9.4
[0m17:20:39.142759 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/wang/.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m17:20:39.144753 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/wang/retail_etl/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:20:39.181514 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.37676227, "process_in_blocks": "87528", "process_kernel_time": 1.098091, "process_mem_max_rss": "90904", "process_out_blocks": "16", "process_user_time": 3.230308}
[0m17:20:39.185530 [debug] [MainThread]: Command `dbt run` failed at 17:20:39.185091 after 0.38 seconds
[0m17:20:39.187042 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f16beefac10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f16be07c970>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f16be07c730>]}
[0m17:20:39.188786 [debug] [MainThread]: Flushing usage events
[0m17:20:40.503497 [debug] [MainThread]: An error was encountered while trying to flush usage events
